### ISSUE TITLE
It seems it is nearly impossible to inject services into controller that extends ResourceController in Symfony 4.3+

### ISSUE THREAD

**Issue by tom10271** [Sylius/SyliusResourceBundle#106]
I am using Symfony 4.3.3 and Sylius 1.5.2. 

```
public function showAction(Request $request, TheServiceINeed $service): Response

// This is not allowed.
// Warning: Declaration of ProductController::showAction(Request $request, TheServiceINeed $service): Response should be compatible with ResourceController::showAction(Request $request): Response
```

I cannot add new arguments to constructor, otherwise
```
Too few arguments to function My\Controller\ProductController::__construct(), 17 passed in
/Users/me/Sites/sylius-app/var/cache/dev/ContainerEReeqxC/getSylius_Controller_ProductService.php 
on line 26 and exactly 21 expected
```

And of course: `$this->get('my_service');`, is not preferred anymore

**Comment by vvasiloi** [comment]
Resource controller services are created by the resource bundle, which injects all dependencies dynamically depending on the resource configuration. If you want to extend the resource controller and inject additional services, you will have to inject yourself the other services as well.

I believe that you might not need to extend the resource controller at all, since it has mainly glue code.

You could probably achieve the same results in other ways. Check out the customization guide: https://docs.sylius.com/en/1.5/customization/index.html

Use the Slack or other support channels if you have more questions: https://docs.sylius.com/en/1.5/support/index.html

**Comment by lchrusciel** [comment]
Right now, I would say, that `$this->get('my_service');` is the preferred option to customize ResourceController due to its architectural structure. 

Nevertheless, I would recommend considering creation just a new controller without the debt of ResourceController.

**Comment by tom10271** [comment]
Well noted. Thank you for answering.
