### ISSUE TITLE
Missing package pagerfanta/doctrine-orm-adapter

### ISSUE THREAD

**Issue by sabat24** [Sylius/SyliusResourceBundle#547]
As I understand from that comment -> https://github.com/BabDev/Pagerfanta/issues/15#issuecomment-685758232 `pagerfanta` since `3.x` version was split into 2 packages: `core` and `twig`. In your `ResourceRepositoryTrait` class there is a reference to `use Pagerfanta\Doctrine\ORM\QueryAdapter;`. However the `babdev/pagerfanta-bundle` on which you rely doesn't use the `pagerfanta/doctrine-orm-adapter` package. 

In my opinion you should add that package directly to your `composer.json` or re-implement the `ResourceRepositoryTrait` class to not use `QueryAdapter`. Without that you will get following exception:

![obraz](https://user-images.githubusercontent.com/6381661/210173759-8bc598ac-10f6-409d-ae77-d6f0542373f4.png)

**Comment by mbabker** [comment]
Because this bundle supports use with the ORM, MongoDB ODM, and PHPCR ODM, having the various Pagerfanta adapters be optional integrations is the correct approach here.  Otherwise, this bundle would have to require `pagerfanta/doctrine-mongodb-odm-adapter`, `pagerfanta/doctrine-orm-adapter`, and `pagerfanta/doctrine-phpcr-odm-adapter` to ensure the dependencies for all of the repository integrations are installed (even if you're only using one of the three).  I imagine that would be a headache for those only using the ORM as the MongoDB ODM requires `ext/mongodb`.

Until support for the two ODM integrations is removed, it'd be better to use a combination of Composer's `suggest` feature and runtime checks (throw an exception if the dependency is missing).  Maybe in 2.0 after the ODM integrations are removed, this bundle can have its dependency list updated to explicitly require the ORM and the Pagerfanta adapter (since the ORM would be the only manager it supports).

**Comment by sabat24** [comment]
> Because this bundle supports use with the ORM, MongoDB ODM, and PHPCR ODM, having the various Pagerfanta adapters be optional integrations is the correct approach here. 

I agree with you. I was a bit confused by doc in which `orm` approach is used as a default one. 

> Remember that the doctrine/orm driver is used by default.
> If you use the "make:entity" command you should have a generated repository which extends ServiceEntityRepository. Then you just have to implement SyliusRepositoryInterface and use ResourceRepositoryTrait.

I supposed that if something is configured by default, it also has got all dependencies  installed. And if you use `ResourceRepositoryTrait` as it was stated, you will get an error. 

To the point, what was my request about:
a) add information to the doc that you should manually install correct adapter - even for a default configuration,
b) or add a default ORM adapter to `composer.json` and add information to the doc, that if you use non-default one you have to install it.

I understand your point to not add anything by default to the bundle, so the "b" point from my list can be ignored. What's more I saw that in next version there is no `ResourceRepositoryTrait` so it may be less confusing.

**Comment by loic425** [comment]
I think it has been fixed here
https://github.com/Sylius/SyliusResourceBundle/pull/700

**Comment by loic425** [comment]
Feel free to reopen that issue if needed.
